export interface Env {
  AI: Ai
  USAGE_KV?: KVNamespace
  SYNC_KV: KVNamespace
  ALLOWED_ORIGIN?: string
  LLM_API_KEY: string
  LLM_API_URL?: string
  LLM_MODEL?: string
  ANTHROPIC_API_KEY?: string
  CLERK_ISSUER_URL: string
  CLERK_JWT_AUDIENCE?: string
  CLERK_SECRET_KEY: string
  STRIPE_SECRET_KEY: string
  STRIPE_WEBHOOK_SECRET: string
  STRIPE_PRO_MONTHLY_PRICE_ID: string
  STRIPE_PRO_YEARLY_PRICE_ID: string
  TAVILY_API_KEY?: string
  JUDILIBRE_API_KEY?: string
  PISTE_OAUTH_CLIENT_ID?: string
  PISTE_OAUTH_CLIENT_SECRET?: string
  ADMIN_EMAIL: string
  VAPID_PUBLIC_KEY?: string
  VAPID_PRIVATE_KEY?: string
  PUSH_SUBSCRIPTIONS?: KVNamespace
  RESEND_API_KEY?: string
  EMAIL_FROM?: string
  LIBRARY_R2?: R2Bucket
  LEGAL_CODES_INDEX?: VectorizeIndex
  ADMIN_API_KEY?: string
  HF_API_TOKEN?: string
}
